version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/bzon/adop-ctl
    steps:  
      - checkout
      - setup_remote_docker
      - run: 
          name: Get dependencies
          command: go get -v -t -d ./...
      - run:
          name: Test
          command: |
            go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}


 
